name: food_diary
description: Coffee Diary app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  image_picker: ^1.1.2

  geolocator: ^14.0.3
  geocoding: ^4.0.0

  url_launcher: ^6.3.1

  shared_preferences: ^2.3.3

  flutter_map: ^8.0.0
  latlong2: ^0.10.1
  http: ^1.6.0
  sign_in_with_apple: ^8.1.0
  crypto: ^3.0.7
  supabase_flutter: ^2.17.1
  uuid: ^4.6.0
  share_plus: ^13.3.0
  flutter_svg: ^2.0.7
  map_launcher: ^6.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/branding/bite_the_way_logo_master.png
    - assets/logo/bite_the_way_logo.svg

# Configuration for automatic launcher icon generation.

flutter_launcher_icons:
  image_path: "assets/images/app_1icon.png"
  android: "launch_background"
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_1icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_1icon.png"

