// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVCObQE63LzAQoqBozG83eZW1-SItHUO8',
    appId: '1:188806948323:web:45836b22055f7b89002cd6',
    messagingSenderId: '188806948323',
    projectId: 'foodiary-91a6b',
    authDomain: 'foodiary-91a6b.firebaseapp.com',
    storageBucket: 'foodiary-91a6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzDwKlQKmpfwM78qio4-tWfD3JBa9Ax8',
    appId: '1:188806948323:android:fb25288f70f34a99002cd6',
    messagingSenderId: '188806948323',
    projectId: 'foodiary-91a6b',
    storageBucket: 'foodiary-91a6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGc5fELWJsOPR2hk41o0k8ABQsbFDpggA',
    appId: '1:188806948323:ios:5476f939f1ae4401002cd6',
    messagingSenderId: '188806948323',
    projectId: 'foodiary-91a6b',
    storageBucket: 'foodiary-91a6b.firebasestorage.app',
    iosBundleId: 'com.dashay.foodiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGc5fELWJsOPR2hk41o0k8ABQsbFDpggA',
    appId: '1:188806948323:ios:db5b3492ecec65ff002cd6',
    messagingSenderId: '188806948323',
    projectId: 'foodiary-91a6b',
    storageBucket: 'foodiary-91a6b.firebasestorage.app',
    iosBundleId: 'com.example.foodDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVCObQE63LzAQoqBozG83eZW1-SItHUO8',
    appId: '1:188806948323:web:0993464c67d2013a002cd6',
    messagingSenderId: '188806948323',
    projectId: 'foodiary-91a6b',
    authDomain: 'foodiary-91a6b.firebaseapp.com',
    storageBucket: 'foodiary-91a6b.firebasestorage.app',
  );
}
